ALTER TABLE chat_channels
  ADD COLUMN IF NOT EXISTS description  TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS type         VARCHAR(20) NOT NULL DEFAULT 'channel',
  ADD COLUMN IF NOT EXISTS is_private   BOOLEAN NOT NULL DEFAULT FALSE;
