import { useEffect, useState } from 'react'
import { Sparkles, Loader2, Info, RefreshCw } from 'lucide-react'
import { aiApi } from '@seestack/shared'
import type { AiAnalysisResult } from '@seestack/shared'

interface Props {
  fingerprint: string
  projectId: string
}

export function AiAnalysisPanel({ fingerprint, projectId }: Props) {
  const [result, setResult] = useState<AiAnalysisResult | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notConfigured, setNotConfigured] = useState(false)

  // On mount: try to load any cached analysis, silently ignore 404.
  useEffect(() => {
    let cancelled = false
    aiApi.cached(fingerprint, projectId)
      .then((r) => { if (!cancelled) setResult(r.data) })
      .catch(() => { /* not cached yet */ })
    return () => { cancelled = true }
  }, [fingerprint, projectId])

  async function analyze(force = false) {
    setLoading(true)
    setError(null)
    setNotConfigured(false)
    try {
      const resp = await aiApi.analyzeError(fingerprint, projectId, force)
      setResult(resp.data)
    } catch (e: any) {
      const code = e?.error?.code
      if (code === 'AI_NOT_CONFIGURED') {
        setNotConfigured(true)
      } else {
        setError(e?.error?.message ?? 'AI analysis failed. Please try again.')
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="mb-4 rounded-lg border"
      style={{ background: 'var(--bg-surface)', borderColor: 'var(--border)' }}>
      <div className="flex flex-wrap items-center justify-between gap-2 border-b px-4 py-2"
        style={{ borderColor: 'var(--border)' }}>
        <span className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider"
          style={{ color: 'var(--text-tertiary)' }}>
          <Sparkles size={12} /> AI Error Assistant
        </span>
        <div className="flex items-center gap-2">
          {result && (
            <button
              onClick={() => analyze(true)}
              disabled={loading}
              className="inline-flex items-center gap-1 rounded-md px-2.5 py-1 text-[11px] font-medium disabled:opacity-50"
              style={{ background: 'var(--bg-hover)', color: 'var(--text-secondary)', border: 'none', cursor: 'pointer' }}>
              <RefreshCw size={11} className={loading ? 'animate-spin' : ''} /> Regenerate
            </button>
          )}
          {!result && (
            <button
              onClick={() => analyze(false)}
              disabled={loading}
              className="inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-[12px] font-medium disabled:opacity-50"
              style={{ background: 'var(--primary)', color: 'white', border: 'none', cursor: 'pointer' }}>
              {loading ? <><Loader2 size={12} className="animate-spin" /> Analyzing…</> : 'Explain & Suggest Fix'}
            </button>
          )}
        </div>
      </div>

      {!result && !loading && !error && !notConfigured && (
        <div className="flex items-start gap-2 px-4 py-3 text-[12px]" style={{ color: 'var(--text-tertiary)' }}>
          <Info size={12} className="mt-0.5" />
          <span>
            Click <b>Explain & Suggest Fix</b> for an AI-generated explanation, root cause, and step-by-step
            remediation. Secrets (tokens, passwords, auth headers) are redacted before sending. Results are
            cached per error.
          </span>
        </div>
      )}

      {loading && !result && (
        <div className="flex items-center gap-2 px-4 py-3 text-[12px]" style={{ color: 'var(--text-tertiary)' }}>
          <Loader2 size={12} className="animate-spin" /> Sending sanitized payload to OpenAI…
        </div>
      )}

      {notConfigured && (
        <div className="px-4 py-3 text-[12px]"
          style={{ background: 'var(--warning-ghost)', color: 'var(--warning)' }}>
          AI analysis is not configured. Set <code>OPENAI_API_KEY</code> on the backend to enable this feature.
        </div>
      )}

      {error && (
        <div className="px-4 py-3 text-[12px]"
          style={{ background: 'var(--danger-ghost)', color: 'var(--danger)' }}>
          {error}
        </div>
      )}

      {result && (
        <div className="space-y-3 p-4">
          <div className="flex flex-wrap items-center gap-2">
            <Pill label={`severity: ${result.severity}`} kind={severityKind(result.severity)} />
            <Pill label={`confidence: ${result.confidence}`} kind={confidenceKind(result.confidence)} />
            {result.cached && <Pill label="cached" kind="muted" />}
            <span className="ms-auto text-[10px]" style={{ color: 'var(--text-tertiary)' }}>
              {result.model ? `Generated by ${result.model}` : ''}
              {result.generatedAt ? ` · ${new Date(result.generatedAt).toLocaleString()}` : ''}
            </span>
          </div>

          <div className="grid gap-3 md:grid-cols-2">
            <Card title="What happened" body={result.explanation} accent="var(--primary)" />
            <Card title="Likely cause" body={result.rootCause} accent="var(--warning)" />
          </div>

          <ListCard title="How to fix" items={result.fixSteps} accent="var(--success)" ordered />
          <ListCard title="How to prevent" items={result.prevention} accent="var(--primary-text)" />
        </div>
      )}
    </div>
  )
}

function Card({ title, body, accent }: { title: string; body: string; accent: string }) {
  return (
    <div className="rounded-md border p-3"
      style={{ background: 'var(--bg-base)', borderColor: 'var(--border)' }}>
      <div className="mb-1 text-[10px] font-semibold uppercase tracking-wider"
        style={{ color: 'var(--text-tertiary)' }}>
        <span className="me-1" style={{ color: accent }}>●</span>{title}
      </div>
      <div className="text-[12px] leading-relaxed" style={{ color: 'var(--text-primary)', whiteSpace: 'pre-wrap' }}>
        {body || '—'}
      </div>
    </div>
  )
}

function ListCard({ title, items, accent, ordered }: {
  title: string; items: string[]; accent: string; ordered?: boolean
}) {
  if (!items || items.length === 0) return null
  const Tag: any = ordered ? 'ol' : 'ul'
  return (
    <div className="rounded-md border p-3"
      style={{ background: 'var(--bg-base)', borderColor: 'var(--border)' }}>
      <div className="mb-1 text-[10px] font-semibold uppercase tracking-wider"
        style={{ color: 'var(--text-tertiary)' }}>
        <span className="me-1" style={{ color: accent }}>●</span>{title}
      </div>
      <Tag className={ordered ? 'list-decimal ps-5' : 'list-disc ps-5'}
        style={{ color: 'var(--text-primary)', fontSize: 12, lineHeight: 1.6 }}>
        {items.map((s, i) => <li key={i}>{s}</li>)}
      </Tag>
    </div>
  )
}

function Pill({ label, kind }: { label: string; kind: 'good' | 'warn' | 'bad' | 'muted' }) {
  const map = {
    good:  { bg: 'var(--success-ghost)', fg: 'var(--success)' },
    warn:  { bg: 'var(--warning-ghost)', fg: 'var(--warning)' },
    bad:   { bg: 'var(--danger-ghost)',  fg: 'var(--danger)' },
    muted: { bg: 'var(--bg-active)',     fg: 'var(--text-secondary)' },
  } as const
  const c = map[kind]
  return (
    <span className="rounded px-1.5 py-0.5 text-[10px] font-medium uppercase"
      style={{ background: c.bg, color: c.fg }}>{label}</span>
  )
}

function severityKind(s: string): 'good' | 'warn' | 'bad' | 'muted' {
  const v = (s ?? '').toLowerCase()
  if (v === 'high') return 'bad'
  if (v === 'medium') return 'warn'
  if (v === 'low') return 'good'
  return 'muted'
}
function confidenceKind(s: string): 'good' | 'warn' | 'bad' | 'muted' {
  const v = (s ?? '').toLowerCase()
  if (v === 'high') return 'good'
  if (v === 'medium') return 'warn'
  if (v === 'low') return 'bad'
  return 'muted'
}
